# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EuxUpHCjlbVrIsHasoWArAZwCZEaF5jW
"""

#from google.colab import drive
#drive.mount('/content/drive')

#import os
#os.chdir("drive/My Drive")

from keras.models import load_model
#model =load_model('drive/My Drive/final_try3')
model =load_model('weights_best1.hdf5')

import cv2
#import matplotlib.pyplot as plt
#import matplotlib.image as mpimg
import numpy as np 
"""
'mess/0020.jpg'
'0016.jpg':volleyball
'audi.jpg':Audi
'0051.jpg':Mess
0: Admin_Block
1: BSNL_Auditorium
3: Volleyball_Ground
4: Hostel_Mess
 """
img = cv2.imread('LPS_v2/audi/0020.jpg')
img=cv2.cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.resize(img,(300,300))
img = np.reshape(img,[300,300,3])
img = img/255.
classes=model.predict(np.expand_dims(img, axis=0))
a=np.argmax(classes)
if int(a)==0:
    print("Admin Block")
elif int(a)==1:
    print("BSNL Auditorium")
elif int(a)==2:
    print("Volleyball Ground")
elif int(a)==3:
    print("Hostel Block")    
#plt.imshow(img);
